### ISSUE TITLE
The function unicode_to_utf8 may contain a bug

### ISSUE THREAD

**Issue by rvillalob** [torvalds/uemacs#15]
I may be mistaken, but I think the function unicode_to_utf8 is broken. Although it is able to generate the continuation bytes of the UTF8 sequence, it fails to produce the correct leading byte.

**Comment by rvillalob** [comment]
The loop's test condition should be
   c >= prefix
Instead of
   C > prefix

**Comment by rfivet** [comment]
You are right. (see https://github.com/rfivet/cigue/commit/2cef0714926cc119c57b096fab3cf70520ff21c5)
