### ISSUE TITLE
C-s and C-x C-s stops uemacs

### ISSUE THREAD

**Issue by smplcdr** [torvalds/uemacs#26]
When I press C-s or C-x C-s, uemacs stops working, I tried to recompile, but it doesn’t help me (I didn’t change anything in the code), it freezes anyway. Does anyone have the same problem? Has anyone found a solution?

**Comment by rfivet** [comment]
Your terminal flow control (Xon/Xoff, C-q/C-s) may be interfering here.
Also if I remember well Xon/Xoff is activated by default in estruct.h, try setting that to 0.

**Comment by smplcdr** [comment]
> Your terminal flow control (Xon/Xoff, C-q/C-s) may be interfering here.
> Also if I remember well Xon/Xoff is activated by default in estruct.h, try setting that to 0.

**Comment by smplcdr** [comment]
> Your terminal flow control (Xon/Xoff, C-q/C-s) may be interfering here.
> Also if I remember well Xon/Xoff is activated by default in estruct.h, try setting that to 0.

I set XONOFF to 0, but it didn't help

**Comment by smplcdr** [comment]
I checked your version of uemacs, and yours uemacs isn't freezing by C-s. It's interesting

**Comment by rvillalob** [comment]
Check this resource about terminal "raw mode":
https://viewsourcecode.org/snaptoken/kilo/02.enteringRawMode.html

**Comment by rfivet** [comment]
If you check "alternative" in ebind.h, you will see that uEmacs/PK avoids key mapping that include C-S and C-q compare to traditional Micro-EMACS. You need modify posix.c to allow C-S/C-q to be passed as key input.

**Comment by smplcdr** [comment]
> Check [rfivet/uemacs@2e2d684](https://github.com/rfivet/uemacs/commit/2e2d68469750de1b017a72aa008c54781aecb904)

Thanx, this fixed the problem
